name: EdenChat
options:
  bundleIdPrefix: ai.jo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.4"

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

targets:
  EdenChat:
    type: application
    platform: iOS
    sources:
      - EdenChat
    settings:
      base:
        INFOPLIST_FILE: EdenChat/Info.plist
        CODE_SIGN_ENTITLEMENTS: EdenChat/EdenChat.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: ai.jo.edenchat
        SWIFT_VERSION: "6.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SUPPORTS_MACCATALYST: "YES"
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: "NO"
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseCore
      - package: firebase-ios-sdk
        product: FirebaseFirestore
      - package: firebase-ios-sdk
        product: FirebaseMessaging
